# Generated by Django 5.2.4 on 2025-09-21 07:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_product_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='product',
        ),
        migrations.RemoveField(
            model_name='review',
            name='rating',
        ),
    ]
