# Generated by Django 5.2.4 on 2025-09-21 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0003_remove_review_product_remove_review_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='price',
            name='price_date',
            field=models.DateField(),
        ),
        migrations.AlterUniqueTogether(
            name='price',
            unique_together={('product', 'price_date')},
        ),
    ]
